M48
; DRILL file {KiCad 8.0.7} date 2025-02-08T02:54:48+1300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-08T02:54:48+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.9874Y-3.4889
X3.9874Y-3.5689
X4.1874Y-3.5289
T2
X2.5197Y-3.3071
X2.5197Y-4.9606
M30
