[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32WB55CG --speed 950"
# runner = "teleprobe local run --chip STM32WB55CG --elf"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
